name: Test

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true

      - name: Create the Keystore
        run: echo $KEYSTORE_BASE64 | base64 -d > $HOME/upload-keystore.jks

      - name: Create key properties
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run: echo $KEY_PROPERTIES > /home/runner/work/yana/yana/android/key.properties

      - name: cat
        run: cat $HOME/upload-keystore.jks
      - name: cat2
        run: cat /home/runner/work/yana/yana/android/key.properties

      - name: flutter pub get
        run: flutter pub get

      - name: flutter build apk
        run: flutter build apk

      - name: flutter build appbundle
        run: flutter build appbundle

      - name: 'Upload apk'
        uses: actions/upload-artifact@v2
        with:
          name: yana
          path: build/app/outputs/flutter-apk

      # - name: 'Upload appbundle'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: yana-appbundle
      #     path: build/app/outputs/bundle/release/app-release.aab
