name: Test

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true
      - run: flutter pub get
#      - run: flutter test
      - run: flutter build apk
#      - run: flutter build appbundle
      - name: 'Upload apk'
        uses: actions/upload-artifact@v2
        with:
          name: yana
          path: build/app/outputs/flutter-apk

      # - name: 'Upload appbundle'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: yana-appbundle
      #     path: build/app/outputs/bundle/release/app-release.aab