name: Test

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true

      - name: echo the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/upload-keystore.jks
      - name: Create key properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEY_PROPERTIES }}
        run: |
          # import keystore from secrets
          echo $KEY_PROPERTIES | base64 -d > $RUNNER_TEMP/key.properties

      - name: flutter pub get
        run: flutter pub get
      - name: flutter build apk
        run: flutter build apk
      - name: flutter build appbundle
        run: flutter build appbundle
      - name: 'Upload apk'
        uses: actions/upload-artifact@v2
        with:
          name: yana
          path: build/app/outputs/flutter-apk

      # - name: 'Upload appbundle'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: yana-appbundle
      #     path: build/app/outputs/bundle/release/app-release.aab
